In [2]:
import pandas as pd
import numpy as np

In [3]:
zillow_msa = pd.read_csv("Data Intermediate/zillow_msa.csv")

In [4]:
zillow_msa.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,Date,HomeValue,Year
0,394913,1,"New York, NY",msa,NY,2000-01-31,217908.609033,2000
1,753899,2,"Los Angeles, CA",msa,CA,2000-01-31,225552.897453,2000
2,394463,3,"Chicago, IL",msa,IL,2000-01-31,155258.141365,2000
3,394514,4,"Dallas, TX",msa,TX,2000-01-31,130734.453703,2000
4,394692,5,"Houston, TX",msa,TX,2000-01-31,125738.933364,2000

In [5]:
zillow_msa.shape

(282504, 8)

In [6]:
zillow_msa.columns

Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName', 'Date',
       'HomeValue', 'Year'],
      dtype='object')

In [7]:
zillow_msa["Date"].min(), zillow_msa["Date"].max()

('2000-01-31', '2026-04-30')

In [8]:
zillow_msa["Date"] = pd.to_datetime(zillow_msa["Date"])

In [9]:
zillow_2010 = zillow_msa[
    zillow_msa["Date"] == "2010-12-31"
].copy()

zillow_2015 = zillow_msa[
    zillow_msa["Date"] == "2015-12-31"
].copy()

In [10]:
zillow_2010.shape, zillow_2015.shape

((894, 8), (894, 8))

In [11]:
zillow_2010.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,Date,HomeValue,Year
117114,394913,1,"New York, NY",msa,NY,2010-12-31,392217.115908,2010
117115,753899,2,"Los Angeles, CA",msa,CA,2010-12-31,398666.631278,2010
117116,394463,3,"Chicago, IL",msa,IL,2010-12-31,190206.220312,2010
117117,394514,4,"Dallas, TX",msa,TX,2010-12-31,149304.484387,2010
117118,394692,5,"Houston, TX",msa,TX,2010-12-31,150137.757352,2010

In [12]:
zillow_2015.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,Date,HomeValue,Year
170754,394913,1,"New York, NY",msa,NY,2015-12-31,428263.745008,2015
170755,753899,2,"Los Angeles, CA",msa,CA,2015-12-31,505439.753601,2015
170756,394463,3,"Chicago, IL",msa,IL,2015-12-31,207197.138214,2015
170757,394514,4,"Dallas, TX",msa,TX,2015-12-31,198993.505462,2015
170758,394692,5,"Houston, TX",msa,TX,2015-12-31,196240.731321,2015

In [13]:
zillow_2010["HomeValue"].isna().sum()

np.int64(110)

In [14]:
zillow_2015["HomeValue"].isna().sum()

np.int64(36)

In [15]:
analysis_2024_top100[["Metro", "CensusMetro"]].head(10)

NameError: name 'analysis_2024_top100' is not defined

In [16]:
analysis_2024_top100 = pd.read_csv(
    "Data Intermediate/analysis_2024_top100.csv"
)

In [17]:
analysis_2024_top100.shape

(100, 14)

In [18]:
analysis_2024_top100.columns

Index(['RegionID', 'SizeRank', 'Metro', 'RegionType', 'StateName', 'Date',
       'HomeValue', 'Year', 'CensusMetro', 'Income2024', 'Population2024',
       'CollegeEducated2024', 'CollegeEducatedPct', 'PriceToIncomeRatio'],
      dtype='object')

In [19]:
analysis_2024_top100[["Metro", "CensusMetro"]].head(10)

              Metro                                   CensusMetro
0      New York, NY            New York-Newark-Jersey City, NY-NJ
1   Los Angeles, CA            Los Angeles-Long Beach-Anaheim, CA
2       Chicago, IL               Chicago-Naperville-Elgin, IL-IN
3        Dallas, TX               Dallas-Fort Worth-Arlington, TX
4       Houston, TX            Houston-Pasadena-The Woodlands, TX
5    Washington, DC  Washington-Arlington-Alexandria, DC-VA-MD-WV
6  Philadelphia, PA   Philadelphia-Camden-Wilmington, PA-NJ-DE-MD
7         Miami, FL     Miami-Fort Lauderdale-West Palm Beach, FL
8       Atlanta, GA             Atlanta-Sandy Springs-Roswell, GA
9        Boston, MA                Boston-Cambridge-Newton, MA-NH

In [20]:
metro_list = analysis_2024_top100["Metro"]

In [21]:
zillow_2010_top100 = zillow_2010[
    zillow_2010["RegionName"].isin(metro_list)
].copy()

zillow_2015_top100 = zillow_2015[
    zillow_2015["RegionName"].isin(metro_list)
].copy()

In [22]:
zillow_2010_top100.shape, zillow_2015_top100.shape

((100, 8), (100, 8))

In [23]:
zillow_2010_top100["HomeValue"].isna().sum()

np.int64(0)

In [24]:
zillow_2015_top100["HomeValue"].isna().sum()

np.int64(0)

In [25]:
metro_mapping = analysis_2024_top100[
    ["Metro", "CensusMetro"]
].copy()

metro_mapping.head()

             Metro                         CensusMetro
0     New York, NY  New York-Newark-Jersey City, NY-NJ
1  Los Angeles, CA  Los Angeles-Long Beach-Anaheim, CA
2      Chicago, IL     Chicago-Naperville-Elgin, IL-IN
3       Dallas, TX     Dallas-Fort Worth-Arlington, TX
4      Houston, TX  Houston-Pasadena-The Woodlands, TX

In [26]:
metro_mapping.shape

(100, 2)

In [27]:
metro_mapping.to_csv(
    "Data Intermediate/metro_mapping.csv",
    index=False
)

In [28]:
zillow_2010_top100.to_csv(
    "Data Intermediate/zillow_2010_top100.csv",
    index=False
)

zillow_2015_top100.to_csv(
    "Data Intermediate/zillow_2015_top100.csv",
    index=False
)

In [29]:
income_2010 = pd.read_csv("Data Raw/Median_income_2010.csv")

In [30]:
income_2010.shape

(1, 749)

In [31]:
income_2010.head()

,Label (Grouping),"Abilene, TX Metro Area!!Estimate","Abilene, TX Metro Area!!Margin of Error","Aguadilla-Isabela-San Sebasti?n, PR Metro Area!!Estimate","Aguadilla-Isabela-San Sebasti?n, PR Metro Area!!Margin of Error","Akron, OH Metro Area!!Estimate","Akron, OH Metro Area!!Margin of Error","Albany, GA Metro Area!!Estimate","Albany, GA Metro Area!!Margin of Error","Albany-Schenectady-Troy, NY Metro Area!!Estimate",...,"Yauco, PR Metro Area!!Estimate","Yauco, PR Metro Area!!Margin of Error","York-Hanover, PA Metro Area!!Estimate","York-Hanover, PA Metro Area!!Margin of Error","Youngstown-Warren-Boardman, OH-PA Metro Area!!Estimate","Youngstown-Warren-Boardman, OH-PA Metro Area!!Margin of Error","Yuba City, CA Metro Area!!Estimate","Yuba City, CA Metro Area!!Margin of Error","Yuma, AZ Metro Area!!Estimate","Yuma, AZ Metro Area!!Margin of Error"
0,Median household income in the past 12 months ...,"42,286","±1,168","13,489",±366,"48,570",±589,"36,828","±1,221","57,781",...,"13,911",±433,"57,494",±817,"41,474",±455,"49,190","±1,309","40,340","±1,162"

In [32]:
income_2010.columns

Index(['Label (Grouping)', 'Abilene, TX Metro Area!!Estimate',
       'Abilene, TX Metro Area!!Margin of Error',
       'Aguadilla-Isabela-San Sebasti?n, PR Metro Area!!Estimate',
       'Aguadilla-Isabela-San Sebasti?n, PR Metro Area!!Margin of Error',
       'Akron, OH Metro Area!!Estimate',
       'Akron, OH Metro Area!!Margin of Error',
       'Albany, GA Metro Area!!Estimate',
       'Albany, GA Metro Area!!Margin of Error',
       'Albany-Schenectady-Troy, NY Metro Area!!Estimate',
       ...
       'Yauco, PR Metro Area!!Estimate',
       'Yauco, PR Metro Area!!Margin of Error',
       'York-Hanover, PA Metro Area!!Estimate',
       'York-Hanover, PA Metro Area!!Margin of Error',
       'Youngstown-Warren-Boardman, OH-PA Metro Area!!Estimate',
       'Youngstown-Warren-Boardman, OH-PA Metro Area!!Margin of Error',
       'Yuba City, CA Metro Area!!Estimate',
       'Yuba City, CA Metro Area!!Margin of Error',
       'Yuma, AZ Metro Area!!Estimate',
       'Yuma, AZ Metro Area!!Margin of Error'],
      dtype='object', length=749)

In [33]:
income_2010.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Columns: 749 entries, Label (Grouping) to Yuma, AZ Metro Area!!Margin of Error
dtypes: object(749)
memory usage: 6.0+ KB

In [34]:
estimate_cols = [
    col for col in income_2010.columns
    if "Estimate" in col
]

In [35]:
len(estimate_cols)

374

In [36]:
income_2010_est = income_2010[estimate_cols]

income_2010_est.shape

(1, 374)

In [37]:
income_2010_tidy = income_2010_est.T.reset_index()

In [38]:
income_2010_tidy.columns = ["CensusMetro", "Income2010"]

In [39]:
income_2010_tidy["CensusMetro"] = (
    income_2010_tidy["CensusMetro"]
    .str.replace(" Metro Area!!Estimate", "", regex=False)
)

In [40]:
income_2010_tidy["Income2010"] = (
    income_2010_tidy["Income2010"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

income_2010_tidy["Income2010"] = pd.to_numeric(
    income_2010_tidy["Income2010"],
    errors="coerce"
)

In [41]:
income_2010_tidy.head()

                           CensusMetro  Income2010
0                          Abilene, TX       42286
1  Aguadilla-Isabela-San Sebasti?n, PR       13489
2                            Akron, OH       48570
3                           Albany, GA       36828
4          Albany-Schenectady-Troy, NY       57781

In [42]:
income_2010_tidy.shape

(374, 2)

In [43]:
income_2010_tidy.dtypes

CensusMetro    object
Income2010      int64
dtype: object

In [44]:
income_matches_2010 = metro_mapping[
    metro_mapping["CensusMetro"].isin(income_2010_tidy["CensusMetro"])
]

income_matches_2010.shape

(63, 2)

In [45]:
missing_income_2010 = metro_mapping[
    ~metro_mapping["CensusMetro"].isin(income_2010_tidy["CensusMetro"])
]

missing_income_2010

                 Metro                                CensusMetro
0         New York, NY         New York-Newark-Jersey City, NY-NJ
1      Los Angeles, CA         Los Angeles-Long Beach-Anaheim, CA
2          Chicago, IL            Chicago-Naperville-Elgin, IL-IN
4          Houston, TX         Houston-Pasadena-The Woodlands, TX
7            Miami, FL  Miami-Fort Lauderdale-West Palm Beach, FL
8          Atlanta, GA          Atlanta-Sandy Springs-Roswell, GA
9           Boston, MA             Boston-Cambridge-Newton, MA-NH
10         Phoenix, AZ                  Phoenix-Mesa-Chandler, AZ
13         Detroit, MI                Detroit-Warren-Dearborn, MI
16       San Diego, CA         San Diego-Chula Vista-Carlsbad, CA
18          Denver, CO               Denver-Aurora-Centennial, CO
19       Baltimore, MD              Baltimore-Columbia-Towson, MD
22       Charlotte, NC          Charlotte-Concord-Gastonia, NC-SC
25      Sacramento, CA            Sacramento-Roseville-Folsom, CA
27      Cincinnati, OH                       Cincinnati, OH-KY-IN
29       Las Vegas, NV    Las Vegas-Henderson-North Las Vegas, NV
32    Indianapolis, IN          Indianapolis-Carmel-Greenwood, IN
33       Cleveland, OH                              Cleveland, OH
36  Virginia Beach, VA   Virginia Beach-Chesapeake-Norfolk, VA-NC
37      Providence, RI                  Providence-Warwick, RI-MA
39       Milwaukee, WI                     Milwaukee-Waukesha, WI
45     New Orleans, LA                   New Orleans-Metairie, LA
46  Salt Lake City, UT                  Salt Lake City-Murray, UT
48         Buffalo, NY                    Buffalo-Cheektowaga, NY
49      Birmingham, AL                             Birmingham, AL
51    Grand Rapids, MI          Grand Rapids-Wyoming-Kentwood, MI
53  Urban Honolulu, HI                         Urban Honolulu, HI
57           Omaha, NE                               Omaha, NE-IA
58      Bridgeport, CT            Bridgeport-Stamford-Danbury, CT
59      Greenville, SC              Greenville-Anderson-Greer, SC
66       New Haven, CT                              New Haven, CT
72      Charleston, SC            Charleston-North Charleston, SC
74        Stockton, CA                          Stockton-Lodi, CA
76      Boise City, ID                             Boise City, ID
83           Ogden, UT                                  Ogden, UT
88           Provo, UT                        Provo-Orem-Lehi, UT
96         Spokane, WA                 Spokane-Spokane Valley, WA

In [46]:
for metro in missing_income_2010["Metro"]:
    city = metro.split(",")[0]

    matches = income_2010_tidy[
        income_2010_tidy["CensusMetro"].str.contains(
            city,
            case=False,
            na=False
        )
    ]["CensusMetro"].tolist()

    print(f"\n{metro}")
    print(matches)

New York, NY
['New York-Northern New Jersey-Long Island, NY-NJ-PA']

Los Angeles, CA
['Los Angeles-Long Beach-Santa Ana, CA']

Chicago, IL
['Chicago-Joliet-Naperville, IL-IN-WI']

Houston, TX
['Houston-Sugar Land-Baytown, TX']

Miami, FL
['Miami-Fort Lauderdale-Pompano Beach, FL']

Atlanta, GA
['Atlanta-Sandy Springs-Marietta, GA']

Boston, MA
['Boston-Cambridge-Quincy, MA-NH']

Phoenix, AZ
['Phoenix-Mesa-Glendale, AZ']

Detroit, MI
['Detroit-Warren-Livonia, MI']

San Diego, CA
['San Diego-Carlsbad-San Marcos, CA']

Denver, CO
['Denver-Aurora-Broomfield, CO']

Baltimore, MD
['Baltimore-Towson, MD']

Charlotte, NC
['Charlotte-Gastonia-Rock Hill, NC-SC', 'Charlottesville, VA']

Sacramento, CA
['Sacramento--Arden-Arcade--Roseville, CA']

Cincinnati, OH
['Cincinnati-Middletown, OH-KY-IN']

Las Vegas, NV
['Las Vegas-Paradise, NV']

Indianapolis, IN
['Indianapolis-Carmel, IN']

Cleveland, OH
['Cleveland, TN', 'Cleveland-Elyria-Mentor, OH']

Virginia Beach, VA
['Virginia Beach-Norfolk-Newport News, VA-NC']

Providence, RI
['Providence-New Bedford-Fall River, RI-MA']

Milwaukee, WI
['Milwaukee-Waukesha-West Allis, WI']

New Orleans, LA
['New Orleans-Metairie-Kenner, LA']

Salt Lake City, UT
['Salt Lake City, UT']

Buffalo, NY
['Buffalo-Niagara Falls, NY']

Birmingham, AL
['Birmingham-Hoover, AL']

Grand Rapids, MI
['Grand Rapids-Wyoming, MI']

Urban Honolulu, HI
[]

Omaha, NE
['Omaha-Council Bluffs, NE-IA']

Bridgeport, CT
['Bridgeport-Stamford-Norwalk, CT']

Greenville, SC
['Greenville, NC', 'Greenville-Mauldin-Easley, SC']

New Haven, CT
['New Haven-Milford, CT']

Charleston, SC
['Charleston, WV', 'Charleston-North Charleston-Summerville, SC']

Stockton, CA
['Stockton, CA']

Boise City, ID
['Boise City-Nampa, ID']

Ogden, UT
['Ogden-Clearfield, UT']

Provo, UT
['Provo-Orem, UT']

Spokane, WA
['Spokane, WA']

In [47]:
income_2010_tidy[
    income_2010_tidy["CensusMetro"].str.contains(
        "Honolulu|HI",
        case=False,
        na=False
    )
]

                                      CensusMetro  Income2010
61            Charlotte-Gastonia-Rock Hill, NC-SC       53471
65            Chicago-Joliet-Naperville, IL-IN-WI       60574
66                                      Chico, CA       43170
99                         Durham-Chapel Hill, NC       50889
135                     Greensboro-High Point, NC       43588
146                  Hickory-Lenoir-Morganton, NC       40346
147                   Hinesville-Fort Stewart, GA       42489
149                                  Honolulu, HI       70093
151                Houma-Bayou Cane-Thibodaux, LA       48058
207                         Madera-Chowchilla, CA       46039
216                             Memphis, TN-MS-AR       46260
219                    Michigan City-La Porte, IN       46014
262   Philadelphia-Camden-Wilmington, PA-NJ-DE-MD       60259
270           Portland-Vancouver-Hillsboro, OR-WA       56275
293            Saginaw-Saginaw Township North, MI       42954
356  Washington-Arlington-Alexandria, DC-VA-MD-WV       85660
361                                   Wichita, KS       48611
362                             Wichita Falls, TX       44064

In [48]:
metro_mapping_2010 = metro_mapping.copy()

metro_mapping_2010["CensusMetro2010"] = metro_mapping_2010["CensusMetro"]

In [49]:
historical_names_2010 = {
    "New York, NY": "New York-Northern New Jersey-Long Island, NY-NJ-PA",
    "Los Angeles, CA": "Los Angeles-Long Beach-Santa Ana, CA",
    "Chicago, IL": "Chicago-Joliet-Naperville, IL-IN-WI",
    "Houston, TX": "Houston-Sugar Land-Baytown, TX",
    "Miami, FL": "Miami-Fort Lauderdale-Pompano Beach, FL",
    "Atlanta, GA": "Atlanta-Sandy Springs-Marietta, GA",
    "Boston, MA": "Boston-Cambridge-Quincy, MA-NH",
    "Phoenix, AZ": "Phoenix-Mesa-Glendale, AZ",
    "Detroit, MI": "Detroit-Warren-Livonia, MI",
    "San Diego, CA": "San Diego-Carlsbad-San Marcos, CA",
    "Denver, CO": "Denver-Aurora-Broomfield, CO",
    "Baltimore, MD": "Baltimore-Towson, MD",
    "Charlotte, NC": "Charlotte-Gastonia-Rock Hill, NC-SC",
    "Sacramento, CA": "Sacramento--Arden-Arcade--Roseville, CA",
    "Cincinnati, OH": "Cincinnati-Middletown, OH-KY-IN",
    "Las Vegas, NV": "Las Vegas-Paradise, NV",
    "Indianapolis, IN": "Indianapolis-Carmel, IN",
    "Cleveland, OH": "Cleveland-Elyria-Mentor, OH",
    "Virginia Beach, VA": "Virginia Beach-Norfolk-Newport News, VA-NC",
    "Providence, RI": "Providence-New Bedford-Fall River, RI-MA",
    "Milwaukee, WI": "Milwaukee-Waukesha-West Allis, WI",
    "New Orleans, LA": "New Orleans-Metairie-Kenner, LA",
    "Salt Lake City, UT": "Salt Lake City, UT",
    "Buffalo, NY": "Buffalo-Niagara Falls, NY",
    "Birmingham, AL": "Birmingham-Hoover, AL",
    "Grand Rapids, MI": "Grand Rapids-Wyoming, MI",
    "Urban Honolulu, HI": "Honolulu, HI",
    "Omaha, NE": "Omaha-Council Bluffs, NE-IA",
    "Bridgeport, CT": "Bridgeport-Stamford-Norwalk, CT",
    "Greenville, SC": "Greenville-Mauldin-Easley, SC",
    "New Haven, CT": "New Haven-Milford, CT",
    "Charleston, SC": "Charleston-North Charleston-Summerville, SC",
    "Stockton, CA": "Stockton, CA",
    "Boise City, ID": "Boise City-Nampa, ID",
    "Ogden, UT": "Ogden-Clearfield, UT",
    "Provo, UT": "Provo-Orem, UT",
    "Spokane, WA": "Spokane, WA"
}

In [50]:
metro_mapping_2010["CensusMetro2010"] = (
    metro_mapping_2010["Metro"]
    .map(historical_names_2010)
    .fillna(metro_mapping_2010["CensusMetro"])
)

In [51]:
matches_2010 = metro_mapping_2010[
    metro_mapping_2010["CensusMetro2010"].isin(
        income_2010_tidy["CensusMetro"]
    )
]

matches_2010.shape

(100, 3)

In [52]:
analysis_2010_top100 = zillow_2010_top100.merge(
    metro_mapping_2010[["Metro", "CensusMetro2010"]],
    left_on="RegionName",
    right_on="Metro",
    how="left"
)

In [53]:
analysis_2010_top100 = analysis_2010_top100.merge(
    income_2010_tidy,
    left_on="CensusMetro2010",
    right_on="CensusMetro",
    how="left"
)

In [54]:
analysis_2010_top100.shape

(100, 12)

In [55]:
analysis_2010_top100["Income2010"].isna().sum()

np.int64(0)

In [56]:
analysis_2010_top100[
    ["RegionName", "CensusMetro2010", "HomeValue", "Income2010"]
].head(10)

,RegionName,CensusMetro2010,HomeValue,Income2010
0,"New York, NY","New York-Northern New Jersey-Long Island, NY-N...",392217.115908,63915
1,"Los Angeles, CA","Los Angeles-Long Beach-Santa Ana, CA",398666.631278,59876
2,"Chicago, IL","Chicago-Joliet-Naperville, IL-IN-WI",190206.220312,60574
3,"Dallas, TX","Dallas-Fort Worth-Arlington, TX",149304.484387,56349
4,"Houston, TX","Houston-Sugar Land-Baytown, TX",150137.757352,55207
5,"Washington, DC","Washington-Arlington-Alexandria, DC-VA-MD-WV",324258.625517,85660
6,"Philadelphia, PA","Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",215077.430781,60259
7,"Miami, FL","Miami-Fort Lauderdale-Pompano Beach, FL",157067.749610,48839
8,"Atlanta, GA","Atlanta-Sandy Springs-Marietta, GA",146278.264919,57550
9,"Boston, MA","Boston-Cambridge-Quincy, MA-NH",337862.147210,69983

In [57]:
analysis_2010_top100.to_csv(
    "Data Intermediate/analysis_2010_top100.csv",
    index=False
)

metro_mapping_2010.to_csv(
    "Data Intermediate/metro_mapping_2010.csv",
    index=False
)

In [58]:
population_2010 = pd.read_csv("Data Raw/Pop_2010.csv")

In [59]:
population_2010.shape

(1, 749)

In [60]:
population_2010.head()

,Label (Grouping),"Abilene, TX Metro Area!!Estimate","Abilene, TX Metro Area!!Margin of Error","Aguadilla-Isabela-San Sebasti?n, PR Metro Area!!Estimate","Aguadilla-Isabela-San Sebasti?n, PR Metro Area!!Margin of Error","Akron, OH Metro Area!!Estimate","Akron, OH Metro Area!!Margin of Error","Albany, GA Metro Area!!Estimate","Albany, GA Metro Area!!Margin of Error","Albany-Schenectady-Troy, NY Metro Area!!Estimate",...,"Yauco, PR Metro Area!!Estimate","Yauco, PR Metro Area!!Margin of Error","York-Hanover, PA Metro Area!!Estimate","York-Hanover, PA Metro Area!!Margin of Error","Youngstown-Warren-Boardman, OH-PA Metro Area!!Estimate","Youngstown-Warren-Boardman, OH-PA Metro Area!!Margin of Error","Yuba City, CA Metro Area!!Estimate","Yuba City, CA Metro Area!!Margin of Error","Yuma, AZ Metro Area!!Estimate","Yuma, AZ Metro Area!!Margin of Error"
0,Total,"163,092",*****,"309,197",*****,"703,093",*****,"157,528",*****,"865,982",...,"109,937",*****,"428,175",*****,"571,975",*****,"164,580",*****,"190,526",*****

In [61]:
population_2010.columns

Index(['Label (Grouping)', 'Abilene, TX Metro Area!!Estimate',
       'Abilene, TX Metro Area!!Margin of Error',
       'Aguadilla-Isabela-San Sebasti?n, PR Metro Area!!Estimate',
       'Aguadilla-Isabela-San Sebasti?n, PR Metro Area!!Margin of Error',
       'Akron, OH Metro Area!!Estimate',
       'Akron, OH Metro Area!!Margin of Error',
       'Albany, GA Metro Area!!Estimate',
       'Albany, GA Metro Area!!Margin of Error',
       'Albany-Schenectady-Troy, NY Metro Area!!Estimate',
       ...
       'Yauco, PR Metro Area!!Estimate',
       'Yauco, PR Metro Area!!Margin of Error',
       'York-Hanover, PA Metro Area!!Estimate',
       'York-Hanover, PA Metro Area!!Margin of Error',
       'Youngstown-Warren-Boardman, OH-PA Metro Area!!Estimate',
       'Youngstown-Warren-Boardman, OH-PA Metro Area!!Margin of Error',
       'Yuba City, CA Metro Area!!Estimate',
       'Yuba City, CA Metro Area!!Margin of Error',
       'Yuma, AZ Metro Area!!Estimate',
       'Yuma, AZ Metro Area!!Margin of Error'],
      dtype='object', length=749)

In [62]:
estimate_cols = [
    col for col in population_2010.columns
    if "Estimate" in col
]

len(estimate_cols)

374

In [63]:
population_2010_est = population_2010[estimate_cols]

population_2010_est.shape

(1, 374)

In [64]:
population_2010_tidy = population_2010_est.T.reset_index()

population_2010_tidy.columns = ["CensusMetro", "Population2010"]

In [65]:
population_2010_tidy["CensusMetro"] = (
    population_2010_tidy["CensusMetro"]
    .str.replace(" Metro Area!!Estimate", "", regex=False)
)

In [66]:
population_2010_tidy["Population2010"] = (
    population_2010_tidy["Population2010"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

population_2010_tidy["Population2010"] = pd.to_numeric(
    population_2010_tidy["Population2010"],
    errors="coerce"
)

In [67]:
population_2010_tidy.head()

                           CensusMetro  Population2010
0                          Abilene, TX          163092
1  Aguadilla-Isabela-San Sebasti?n, PR          309197
2                            Akron, OH          703093
3                           Albany, GA          157528
4          Albany-Schenectady-Troy, NY          865982

In [68]:
population_2010_tidy.shape

(374, 2)

In [69]:
population_2010_tidy.dtypes

CensusMetro       object
Population2010     int64
dtype: object

In [70]:
analysis_2010_top100 = analysis_2010_top100.merge(
    population_2010_tidy,
    left_on="CensusMetro2010",
    right_on="CensusMetro",
    how="left"
)

In [71]:
analysis_2010_top100.shape

(100, 14)

In [72]:
analysis_2010_top100["Population2010"].isna().sum()

np.int64(0)

In [73]:
analysis_2010_top100[
    ["RegionName", "Income2010", "Population2010"]
].head(10)

         RegionName  Income2010  Population2010
0      New York, NY       63915        18700715
1   Los Angeles, CA       59876        12723781
2       Chicago, IL       60574         9384661
3        Dallas, TX       56349         6154265
4       Houston, TX       55207         5709313
5    Washington, DC       85660         5416691
6  Philadelphia, PA       60259         5911638
7         Miami, FL       48839         5478869
8       Atlanta, GA       57550         5125113
9        Boston, MA       69983         4489250

In [74]:
education_2010 = pd.read_csv("Data Raw/Education_2010.csv")

In [75]:
education_2010.shape

(25, 749)

In [76]:
education_2010.head()

,Label (Grouping),"Abilene, TX Metro Area!!Estimate","Abilene, TX Metro Area!!Margin of Error","Aguadilla-Isabela-San Sebasti?n, PR Metro Area!!Estimate","Aguadilla-Isabela-San Sebasti?n, PR Metro Area!!Margin of Error","Akron, OH Metro Area!!Estimate","Akron, OH Metro Area!!Margin of Error","Albany, GA Metro Area!!Estimate","Albany, GA Metro Area!!Margin of Error","Albany-Schenectady-Troy, NY Metro Area!!Estimate",...,"Yauco, PR Metro Area!!Estimate","Yauco, PR Metro Area!!Margin of Error","York-Hanover, PA Metro Area!!Estimate","York-Hanover, PA Metro Area!!Margin of Error","Youngstown-Warren-Boardman, OH-PA Metro Area!!Estimate","Youngstown-Warren-Boardman, OH-PA Metro Area!!Margin of Error","Yuba City, CA Metro Area!!Estimate","Yuba City, CA Metro Area!!Margin of Error","Yuma, AZ Metro Area!!Estimate","Yuma, AZ Metro Area!!Margin of Error"
0,Total:,"104,387","±1,049","203,050","±1,036","471,659","±1,401","103,864","±2,668","588,842",...,"69,273","±1,151","297,234",±746,"393,821",±973,"103,836","±1,301","120,795",±342
1,No schooling completed,"1,383",±763,"5,164","±1,018","3,145",±667,"1,832",±742,"4,415",...,"1,688",±706,"2,537",±774,"2,167",±588,"2,254",±553,"2,357",±727
2,Nursery school,15,±27,0,±285,0,±269,116,±138,0,...,68,±113,0,±246,38,±62,46,±78,88,±151
3,Kindergarten,0,±294,398,±262,136,±226,0,±300,124,...,0,±285,70,±114,39,±66,0,±294,0,±305
4,1st grade,122,±151,"1,471",±640,0,±269,80,±132,151,...,451,±328,0,±246,73,±94,0,±294,911,±632

In [77]:
education_2010.columns

Index(['Label (Grouping)', 'Abilene, TX Metro Area!!Estimate',
       'Abilene, TX Metro Area!!Margin of Error',
       'Aguadilla-Isabela-San Sebasti?n, PR Metro Area!!Estimate',
       'Aguadilla-Isabela-San Sebasti?n, PR Metro Area!!Margin of Error',
       'Akron, OH Metro Area!!Estimate',
       'Akron, OH Metro Area!!Margin of Error',
       'Albany, GA Metro Area!!Estimate',
       'Albany, GA Metro Area!!Margin of Error',
       'Albany-Schenectady-Troy, NY Metro Area!!Estimate',
       ...
       'Yauco, PR Metro Area!!Estimate',
       'Yauco, PR Metro Area!!Margin of Error',
       'York-Hanover, PA Metro Area!!Estimate',
       'York-Hanover, PA Metro Area!!Margin of Error',
       'Youngstown-Warren-Boardman, OH-PA Metro Area!!Estimate',
       'Youngstown-Warren-Boardman, OH-PA Metro Area!!Margin of Error',
       'Yuba City, CA Metro Area!!Estimate',
       'Yuba City, CA Metro Area!!Margin of Error',
       'Yuma, AZ Metro Area!!Estimate',
       'Yuma, AZ Metro Area!!Margin of Error'],
      dtype='object', length=749)

In [78]:
education_2010["Label (Grouping)"].tolist()

['Total:',
 '\xa0\xa0\xa0\xa0No schooling completed',
 '\xa0\xa0\xa0\xa0Nursery school',
 '\xa0\xa0\xa0\xa0Kindergarten',
 '\xa0\xa0\xa0\xa01st grade',
 '\xa0\xa0\xa0\xa02nd grade',
 '\xa0\xa0\xa0\xa03rd grade',
 '\xa0\xa0\xa0\xa04th grade',
 '\xa0\xa0\xa0\xa05th grade',
 '\xa0\xa0\xa0\xa06th grade',
 '\xa0\xa0\xa0\xa07th grade',
 '\xa0\xa0\xa0\xa08th grade',
 '\xa0\xa0\xa0\xa09th grade',
 '\xa0\xa0\xa0\xa010th grade',
 '\xa0\xa0\xa0\xa011th grade',
 '\xa0\xa0\xa0\xa012th grade, no diploma',
 '\xa0\xa0\xa0\xa0Regular high school diploma',
 '\xa0\xa0\xa0\xa0GED or alternative credential',
 '\xa0\xa0\xa0\xa0Some college, less than 1 year',
 '\xa0\xa0\xa0\xa0Some college, 1 or more years, no degree',
 "\xa0\xa0\xa0\xa0Associate's degree",
 "\xa0\xa0\xa0\xa0Bachelor's degree",
 "\xa0\xa0\xa0\xa0Master's degree",
 '\xa0\xa0\xa0\xa0Professional school degree',
 '\xa0\xa0\xa0\xa0Doctorate degree']

In [79]:
education_2010["Label_clean"] = (
    education_2010["Label (Grouping)"]
    .astype(str)
    .str.replace("\xa0", "", regex=False)
    .str.strip()
)

In [80]:
education_2010[["Label (Grouping)", "Label_clean"]].tail(8)

,Label (Grouping),Label_clean
17,GED or alternative credential,GED or alternative credential
18,"Some college, less than 1 year","Some college, less than 1 year"
19,"Some college, 1 or more years, no degree","Some college, 1 or more years, no degree"
20,Associate's degree,Associate's degree
21,Bachelor's degree,Bachelor's degree
22,Master's degree,Master's degree
23,Professional school degree,Professional school degree
24,Doctorate degree,Doctorate degree

In [81]:
estimate_cols = [
    col for col in education_2010.columns
    if "Estimate" in col
]

In [82]:
total_row = education_2010[
    education_2010["Label_clean"] == "Total:"
][estimate_cols]

college_rows = education_2010[
    education_2010["Label_clean"].isin([
        "Bachelor's degree",
        "Master's degree",
        "Professional school degree",
        "Doctorate degree"
    ])
][estimate_cols]

In [84]:
total_row.shape

(1, 374)

In [85]:
college_rows.shape

(4, 374)

In [86]:
total_numeric = (
    total_row
    .replace(",", "", regex=True)
    .apply(pd.to_numeric, errors="coerce")
)

college_numeric = (
    college_rows
    .replace(",", "", regex=True)
    .apply(pd.to_numeric, errors="coerce")
)

In [87]:
college_total = college_numeric.sum(axis=0)

In [88]:
college_pct = (
    college_total / total_numeric.iloc[0]
) * 100

In [89]:
college_pct.head()

Abilene, TX Metro Area!!Estimate                            20.894364
Aguadilla-Isabela-San Sebasti?n, PR Metro Area!!Estimate    16.005417
Akron, OH Metro Area!!Estimate                              28.513396
Albany, GA Metro Area!!Estimate                             15.819726
Albany-Schenectady-Troy, NY Metro Area!!Estimate            33.180208
dtype: float64

In [90]:
education_2010_tidy = college_pct.reset_index()

education_2010_tidy.columns = [
    "CensusMetro",
    "CollegeEducatedPct2010"
]

In [91]:
education_2010_tidy["CensusMetro"] = (
    education_2010_tidy["CensusMetro"]
    .str.replace(" Metro Area!!Estimate", "", regex=False)
)

In [92]:
education_2010_tidy.head()

                           CensusMetro  CollegeEducatedPct2010
0                          Abilene, TX               20.894364
1  Aguadilla-Isabela-San Sebasti?n, PR               16.005417
2                            Akron, OH               28.513396
3                           Albany, GA               15.819726
4          Albany-Schenectady-Troy, NY               33.180208

In [93]:
education_2010_tidy.shape

(374, 2)

In [94]:
education_2010_tidy.dtypes

CensusMetro                object
CollegeEducatedPct2010    float64
dtype: object

In [95]:
analysis_2010_top100 = analysis_2010_top100.merge(
    education_2010_tidy,
    left_on="CensusMetro2010",
    right_on="CensusMetro",
    how="left"
)

In [96]:
analysis_2010_top100.shape

(100, 16)

In [97]:
analysis_2010_top100["CollegeEducatedPct2010"].isna().sum()

np.int64(0)

In [98]:
analysis_2010_top100[
    [
        "RegionName",
        "HomeValue",
        "Income2010",
        "Population2010",
        "CollegeEducatedPct2010"
    ]
].head(10)

,RegionName,HomeValue,Income2010,Population2010,CollegeEducatedPct2010
0,"New York, NY",392217.115908,63915,18700715,35.964460
1,"Los Angeles, CA",398666.631278,59876,12723781,30.954759
2,"Chicago, IL",190206.220312,60574,9384661,33.964616
3,"Dallas, TX",149304.484387,56349,6154265,31.114052
4,"Houston, TX",150137.757352,55207,5709313,28.428865
5,"Washington, DC",324258.625517,85660,5416691,46.794904
6,"Philadelphia, PA",215077.430781,60259,5911638,33.115289
7,"Miami, FL",157067.749610,48839,5478869,28.107808
8,"Atlanta, GA",146278.264919,57550,5125113,34.134623
9,"Boston, MA",337862.147210,69983,4489250,43.006648

In [99]:
analysis_2010_top100["PriceToIncomeRatio2010"] = (
    analysis_2010_top100["HomeValue"]
    / analysis_2010_top100["Income2010"]
)

In [100]:
analysis_2010_top100[
    [
        "RegionName",
        "HomeValue",
        "Income2010",
        "Population2010",
        "CollegeEducatedPct2010",
        "PriceToIncomeRatio2010"
    ]
].head(10)

,RegionName,HomeValue,Income2010,Population2010,CollegeEducatedPct2010,PriceToIncomeRatio2010
0,"New York, NY",392217.115908,63915,18700715,35.964460,6.136543
1,"Los Angeles, CA",398666.631278,59876,12723781,30.954759,6.658204
2,"Chicago, IL",190206.220312,60574,9384661,33.964616,3.140064
3,"Dallas, TX",149304.484387,56349,6154265,31.114052,2.649639
4,"Houston, TX",150137.757352,55207,5709313,28.428865,2.719542
5,"Washington, DC",324258.625517,85660,5416691,46.794904,3.785415
6,"Philadelphia, PA",215077.430781,60259,5911638,33.115289,3.569217
7,"Miami, FL",157067.749610,48839,5478869,28.107808,3.216031
8,"Atlanta, GA",146278.264919,57550,5125113,34.134623,2.541760
9,"Boston, MA",337862.147210,69983,4489250,43.006648,4.827775

In [101]:
analysis_2010_top100[
    [
        "HomeValue",
        "Income2010",
        "Population2010",
        "CollegeEducatedPct2010",
        "PriceToIncomeRatio2010"
    ]
].isna().sum()

HomeValue                 0
Income2010                0
Population2010            0
CollegeEducatedPct2010    0
PriceToIncomeRatio2010    0
dtype: int64

In [102]:
analysis_2010_top100.to_csv(
    "Data Intermediate/analysis_2010_top100.csv",
    index=False
)

In [103]:
income_2015 = pd.read_csv("Data Raw/Median_income_2015.csv")

In [104]:
income_2015.head()

,Label (Grouping),"Abilene, TX Metro Area!!Estimate","Abilene, TX Metro Area!!Margin of Error","Aguadilla-Isabela, PR Metro Area!!Estimate","Aguadilla-Isabela, PR Metro Area!!Margin of Error","Akron, OH Metro Area!!Estimate","Akron, OH Metro Area!!Margin of Error","Albany, GA Metro Area!!Estimate","Albany, GA Metro Area!!Margin of Error","Albany, OR Metro Area!!Estimate",...,"Yakima, WA Metro Area!!Estimate","Yakima, WA Metro Area!!Margin of Error","York-Hanover, PA Metro Area!!Estimate","York-Hanover, PA Metro Area!!Margin of Error","Youngstown-Warren-Boardman, OH-PA Metro Area!!Estimate","Youngstown-Warren-Boardman, OH-PA Metro Area!!Margin of Error","Yuba City, CA Metro Area!!Estimate","Yuba City, CA Metro Area!!Margin of Error","Yuma, AZ Metro Area!!Estimate","Yuma, AZ Metro Area!!Margin of Error"
0,Median household income in the past 12 months ...,"44,799","±1,146","15,616",±344,"51,160",±559,"37,404","±1,010","45,644",...,"44,749","±1,242","58,269",±741,"42,609",±444,"49,781","±1,809","40,743","±1,111"

In [107]:
income_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Columns: 777 entries, Label (Grouping) to Yuma, AZ Metro Area!!Margin of Error
dtypes: object(777)
memory usage: 6.2+ KB

In [109]:
income_2015.shape

(1, 777)

In [110]:
estimate_cols = [
    col for col in income_2015.columns
    if "Estimate" in col
]

len(estimate_cols)

388

In [111]:
income_2015_est = income_2015[estimate_cols]

income_2015_est.shape

(1, 388)

In [112]:
income_2015_tidy = income_2015_est.T.reset_index()

income_2015_tidy.columns = ["CensusMetro", "Income2015"]

In [113]:
income_2015_tidy["CensusMetro"] = (
    income_2015_tidy["CensusMetro"]
    .str.replace(" Metro Area!!Estimate", "", regex=False)
)

In [114]:
income_2015_tidy["Income2015"] = (
    income_2015_tidy["Income2015"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

income_2015_tidy["Income2015"] = pd.to_numeric(
    income_2015_tidy["Income2015"],
    errors="coerce"
)

In [115]:
income_2015_tidy.head()

             CensusMetro  Income2015
0            Abilene, TX       44799
1  Aguadilla-Isabela, PR       15616
2              Akron, OH       51160
3             Albany, GA       37404
4             Albany, OR       45644

In [116]:
income_2015_tidy.shape

(388, 2)

In [117]:
income_2015_tidy.dtypes

CensusMetro    object
Income2015      int64
dtype: object

In [118]:
income_matches_2015 = metro_mapping[
    metro_mapping["CensusMetro"].isin(income_2015_tidy["CensusMetro"])
]

income_matches_2015.shape

(71, 2)

In [119]:
missing_income_2015 = metro_mapping[
    ~metro_mapping["CensusMetro"].isin(income_2015_tidy["CensusMetro"])
]

missing_income_2015

                 Metro                               CensusMetro
0         New York, NY        New York-Newark-Jersey City, NY-NJ
2          Chicago, IL           Chicago-Naperville-Elgin, IL-IN
4          Houston, TX        Houston-Pasadena-The Woodlands, TX
10         Phoenix, AZ                 Phoenix-Mesa-Chandler, AZ
11   San Francisco, CA         San Francisco-Oakland-Fremont, CA
16       San Diego, CA        San Diego-Chula Vista-Carlsbad, CA
18          Denver, CO              Denver-Aurora-Centennial, CO
25      Sacramento, CA           Sacramento-Roseville-Folsom, CA
28          Austin, TX          Austin-Round Rock-San Marcos, TX
29       Las Vegas, NV   Las Vegas-Henderson-North Las Vegas, NV
32    Indianapolis, IN         Indianapolis-Carmel-Greenwood, IN
33       Cleveland, OH                             Cleveland, OH
36  Virginia Beach, VA  Virginia Beach-Chesapeake-Norfolk, VA-NC
39       Milwaukee, WI                    Milwaukee-Waukesha, WI
41         Raleigh, NC                          Raleigh-Cary, NC
46  Salt Lake City, UT                 Salt Lake City-Murray, UT
48         Buffalo, NY                   Buffalo-Cheektowaga, NY
49      Birmingham, AL                            Birmingham, AL
51    Grand Rapids, MI         Grand Rapids-Wyoming-Kentwood, MI
56       Worcester, MA                             Worcester, MA
57           Omaha, NE                              Omaha, NE-IA
58      Bridgeport, CT           Bridgeport-Stamford-Danbury, CT
59      Greenville, SC             Greenville-Anderson-Greer, SC
61     Bakersfield, CA                    Bakersfield-Delano, CA
66       New Haven, CT                             New Haven, CT
71      North Port, FL         North Port-Bradenton-Sarasota, FL
83           Ogden, UT                                 Ogden, UT
88           Provo, UT                       Provo-Orem-Lehi, UT
97        Scranton, PA                Scranton--Wilkes-Barre, PA

In [120]:
metro_mapping_2015 = metro_mapping.copy()

metro_mapping_2015["CensusMetro2015"] = (
    metro_mapping_2015["CensusMetro"]
)

In [121]:
for metro in missing_income_2015["Metro"]:
    city = metro.split(",")[0]

    matches = income_2015_tidy[
        income_2015_tidy["CensusMetro"].str.contains(
            city,
            case=False,
            na=False
        )
    ]["CensusMetro"].tolist()

    print(f"\n{metro}")
    print(matches)

New York, NY
['New York-Newark-Jersey City, NY-NJ-PA']

Chicago, IL
['Chicago-Naperville-Elgin, IL-IN-WI']

Houston, TX
['Houston-The Woodlands-Sugar Land, TX']

Phoenix, AZ
['Phoenix-Mesa-Scottsdale, AZ']

San Francisco, CA
['San Francisco-Oakland-Hayward, CA']

San Diego, CA
['San Diego-Carlsbad, CA']

Denver, CO
['Denver-Aurora-Lakewood, CO']

Sacramento, CA
['Sacramento--Roseville--Arden-Arcade, CA']

Austin, TX
['Austin-Round Rock, TX']

Las Vegas, NV
['Las Vegas-Henderson-Paradise, NV']

Indianapolis, IN
['Indianapolis-Carmel-Anderson, IN']

Cleveland, OH
['Cleveland, TN', 'Cleveland-Elyria, OH']

Virginia Beach, VA
['Virginia Beach-Norfolk-Newport News, VA-NC']

Milwaukee, WI
['Milwaukee-Waukesha-West Allis, WI']

Raleigh, NC
['Raleigh, NC']

Salt Lake City, UT
['Salt Lake City, UT']

Buffalo, NY
['Buffalo-Cheektowaga-Niagara Falls, NY']

Birmingham, AL
['Birmingham-Hoover, AL']

Grand Rapids, MI
['Grand Rapids-Wyoming, MI']

Worcester, MA
['Worcester, MA-CT']

Omaha, NE
['Omaha-Council Bluffs, NE-IA']

Bridgeport, CT
['Bridgeport-Stamford-Norwalk, CT']

Greenville, SC
['Greenville, NC', 'Greenville-Anderson-Mauldin, SC']

Bakersfield, CA
['Bakersfield, CA']

New Haven, CT
['New Haven-Milford, CT']

North Port, FL
['North Port-Sarasota-Bradenton, FL']

Ogden, UT
['Ogden-Clearfield, UT']

Provo, UT
['Provo-Orem, UT']

Scranton, PA
['Scranton--Wilkes-Barre--Hazleton, PA']

In [122]:
historical_names_2015 = {
    "New York, NY": "New York-Newark-Jersey City, NY-NJ-PA",
    "Chicago, IL": "Chicago-Naperville-Elgin, IL-IN-WI",
    "Houston, TX": "Houston-The Woodlands-Sugar Land, TX",
    "Phoenix, AZ": "Phoenix-Mesa-Scottsdale, AZ",
    "San Francisco, CA": "San Francisco-Oakland-Hayward, CA",
    "San Diego, CA": "San Diego-Carlsbad, CA",
    "Denver, CO": "Denver-Aurora-Lakewood, CO",
    "Sacramento, CA": "Sacramento--Roseville--Arden-Arcade, CA",
    "Austin, TX": "Austin-Round Rock, TX",
    "Las Vegas, NV": "Las Vegas-Henderson-Paradise, NV",
    "Indianapolis, IN": "Indianapolis-Carmel-Anderson, IN",
    "Cleveland, OH": "Cleveland-Elyria, OH",
    "Virginia Beach, VA": "Virginia Beach-Norfolk-Newport News, VA-NC",
    "Milwaukee, WI": "Milwaukee-Waukesha-West Allis, WI",
    "Raleigh, NC": "Raleigh, NC",
    "Salt Lake City, UT": "Salt Lake City, UT",
    "Buffalo, NY": "Buffalo-Cheektowaga-Niagara Falls, NY",
    "Birmingham, AL": "Birmingham-Hoover, AL",
    "Grand Rapids, MI": "Grand Rapids-Wyoming, MI",
    "Worcester, MA": "Worcester, MA-CT",
    "Omaha, NE": "Omaha-Council Bluffs, NE-IA",
    "Bridgeport, CT": "Bridgeport-Stamford-Norwalk, CT",
    "Greenville, SC": "Greenville-Anderson-Mauldin, SC",
    "Bakersfield, CA": "Bakersfield, CA",
    "New Haven, CT": "New Haven-Milford, CT",
    "North Port, FL": "North Port-Sarasota-Bradenton, FL",
    "Ogden, UT": "Ogden-Clearfield, UT",
    "Provo, UT": "Provo-Orem, UT",
    "Scranton, PA": "Scranton--Wilkes-Barre--Hazleton, PA"
}

In [123]:
metro_mapping_2015["CensusMetro2015"] = (
    metro_mapping_2015["Metro"]
    .map(historical_names_2015)
    .fillna(metro_mapping_2015["CensusMetro"])
)

In [124]:
matches_2015 = metro_mapping_2015[
    metro_mapping_2015["CensusMetro2015"].isin(
        income_2015_tidy["CensusMetro"]
    )
]

matches_2015.shape

(100, 3)

In [125]:
metro_mapping_2015.to_csv(
    "Data Intermediate/metro_mapping_2015.csv",
    index=False
)

In [126]:
analysis_2015_top100 = zillow_2015_top100.merge(
    metro_mapping_2015[["Metro", "CensusMetro2015"]],
    left_on="RegionName",
    right_on="Metro",
    how="left"
)

In [127]:
analysis_2015_top100 = analysis_2015_top100.merge(
    income_2015_tidy,
    left_on="CensusMetro2015",
    right_on="CensusMetro",
    how="left"
)

In [128]:
analysis_2015_top100.shape

(100, 12)

In [129]:
analysis_2015_top100["Income2015"].isna().sum()

np.int64(0)

In [130]:
analysis_2015_top100[
    ["RegionName", "CensusMetro2015", "HomeValue", "Income2015"]
].head(10)

,RegionName,CensusMetro2015,HomeValue,Income2015
0,"New York, NY","New York-Newark-Jersey City, NY-NJ-PA",428263.745008,67296
1,"Los Angeles, CA","Los Angeles-Long Beach-Anaheim, CA",505439.753601,60705
2,"Chicago, IL","Chicago-Naperville-Elgin, IL-IN-WI",207197.138214,61828
3,"Dallas, TX","Dallas-Fort Worth-Arlington, TX",198993.505462,59946
4,"Houston, TX","Houston-The Woodlands-Sugar Land, TX",196240.731321,59649
5,"Washington, DC","Washington-Arlington-Alexandria, DC-VA-MD-WV",387927.724986,92324
6,"Philadelphia, PA","Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",216141.501149,62513
7,"Miami, FL","Miami-Fort Lauderdale-West Palm Beach, FL",236156.840184,48745
8,"Atlanta, GA","Atlanta-Sandy Springs-Roswell, GA",188607.438303,57000
9,"Boston, MA","Boston-Cambridge-Newton, MA-NH",410524.555428,75389

In [131]:
population_2015 = pd.read_csv("Data Raw/Pop_2015.csv")

In [132]:
population_2015.shape

(1, 777)

In [133]:
population_2015.head()

,Label (Grouping),"Abilene, TX Metro Area!!Estimate","Abilene, TX Metro Area!!Margin of Error","Aguadilla-Isabela, PR Metro Area!!Estimate","Aguadilla-Isabela, PR Metro Area!!Margin of Error","Akron, OH Metro Area!!Estimate","Akron, OH Metro Area!!Margin of Error","Albany, GA Metro Area!!Estimate","Albany, GA Metro Area!!Margin of Error","Albany, OR Metro Area!!Estimate",...,"Yakima, WA Metro Area!!Estimate","Yakima, WA Metro Area!!Margin of Error","York-Hanover, PA Metro Area!!Estimate","York-Hanover, PA Metro Area!!Margin of Error","Youngstown-Warren-Boardman, OH-PA Metro Area!!Estimate","Youngstown-Warren-Boardman, OH-PA Metro Area!!Margin of Error","Yuba City, CA Metro Area!!Estimate","Yuba City, CA Metro Area!!Margin of Error","Yuma, AZ Metro Area!!Estimate","Yuma, AZ Metro Area!!Margin of Error"
0,Total,"167,945",*****,"325,921",*****,"703,744",*****,"155,917",*****,"118,971",...,"247,408",*****,"439,660",*****,"556,243",*****,"168,684",*****,"202,987",*****

In [134]:
population_2015.columns

Index(['Label (Grouping)', 'Abilene, TX Metro Area!!Estimate',
       'Abilene, TX Metro Area!!Margin of Error',
       'Aguadilla-Isabela, PR Metro Area!!Estimate',
       'Aguadilla-Isabela, PR Metro Area!!Margin of Error',
       'Akron, OH Metro Area!!Estimate',
       'Akron, OH Metro Area!!Margin of Error',
       'Albany, GA Metro Area!!Estimate',
       'Albany, GA Metro Area!!Margin of Error',
       'Albany, OR Metro Area!!Estimate',
       ...
       'Yakima, WA Metro Area!!Estimate',
       'Yakima, WA Metro Area!!Margin of Error',
       'York-Hanover, PA Metro Area!!Estimate',
       'York-Hanover, PA Metro Area!!Margin of Error',
       'Youngstown-Warren-Boardman, OH-PA Metro Area!!Estimate',
       'Youngstown-Warren-Boardman, OH-PA Metro Area!!Margin of Error',
       'Yuba City, CA Metro Area!!Estimate',
       'Yuba City, CA Metro Area!!Margin of Error',
       'Yuma, AZ Metro Area!!Estimate',
       'Yuma, AZ Metro Area!!Margin of Error'],
      dtype='object', length=777)

In [135]:
estimate_cols = [
    col for col in population_2015.columns
    if "Estimate" in col
]

population_2015_est = population_2015[estimate_cols]

population_2015_est.shape

(1, 388)

In [136]:
population_2015_tidy = population_2015_est.T.reset_index()

population_2015_tidy.columns = [
    "CensusMetro",
    "Population2015"
]

In [137]:
population_2015_tidy["CensusMetro"] = (
    population_2015_tidy["CensusMetro"]
    .str.replace(" Metro Area!!Estimate", "", regex=False)
)

In [138]:
population_2015_tidy["Population2015"] = (
    population_2015_tidy["Population2015"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

population_2015_tidy["Population2015"] = pd.to_numeric(
    population_2015_tidy["Population2015"],
    errors="coerce"
)

In [139]:
population_2015_tidy.head()

             CensusMetro  Population2015
0            Abilene, TX          167945
1  Aguadilla-Isabela, PR          325921
2              Akron, OH          703744
3             Albany, GA          155917
4             Albany, OR          118971

In [140]:
population_2015_tidy.shape

(388, 2)

In [141]:
population_2015_tidy.dtypes

CensusMetro       object
Population2015     int64
dtype: object

In [142]:
analysis_2015_top100 = analysis_2015_top100.merge(
    population_2015_tidy,
    left_on="CensusMetro2015",
    right_on="CensusMetro",
    how="left"
)

In [143]:
analysis_2015_top100.shape

(100, 14)

In [144]:
analysis_2015_top100["Population2015"].isna().sum()

np.int64(0)

In [145]:
analysis_2015_top100[
    ["RegionName", "Income2015", "Population2015"]
].head(10)

         RegionName  Income2015  Population2015
0      New York, NY       67296        19979950
1   Los Angeles, CA       60705        13154457
2       Chicago, IL       61828         9534008
3        Dallas, TX       59946         6833420
4       Houston, TX       59649         6346653
5    Washington, DC       92324         5949403
6  Philadelphia, PA       62513         6035680
7         Miami, FL       48745         5861000
8       Atlanta, GA       57000         5535837
9        Boston, MA       75389         4694565

In [146]:
education_2015 = pd.read_csv("Data Raw/Education_2015.csv")

In [147]:
education_2015.shape

(25, 777)

In [148]:
education_2015.head()

,Label (Grouping),"Abilene, TX Metro Area!!Estimate","Abilene, TX Metro Area!!Margin of Error","Aguadilla-Isabela, PR Metro Area!!Estimate","Aguadilla-Isabela, PR Metro Area!!Margin of Error","Akron, OH Metro Area!!Estimate","Akron, OH Metro Area!!Margin of Error","Albany, GA Metro Area!!Estimate","Albany, GA Metro Area!!Margin of Error","Albany, OR Metro Area!!Estimate",...,"Yakima, WA Metro Area!!Estimate","Yakima, WA Metro Area!!Margin of Error","York-Hanover, PA Metro Area!!Estimate","York-Hanover, PA Metro Area!!Margin of Error","Youngstown-Warren-Boardman, OH-PA Metro Area!!Estimate","Youngstown-Warren-Boardman, OH-PA Metro Area!!Margin of Error","Yuba City, CA Metro Area!!Estimate","Yuba City, CA Metro Area!!Margin of Error","Yuma, AZ Metro Area!!Estimate","Yuma, AZ Metro Area!!Margin of Error"
0,Total:,"105,417",±215,"222,309",*****,"477,129",±136,"99,803",±242,"80,945",...,"148,078",±120,"302,842",±48,"391,393",±262,"105,964",±171,"125,410",±208
1,No schooling completed,"1,860",±304,"7,234",±587,"3,601",±374,"1,577",±298,558,...,"5,212",±571,"2,553",±317,"3,274",±377,"3,760",±401,"2,897",±360
2,Nursery school,1,±4,63,±50,31,±26,16,±19,33,...,39,±29,36,±40,28,±24,49,±58,11,±16
3,Kindergarten,18,±21,171,±98,37,±36,0,±30,14,...,100,±118,28,±30,0,±27,41,±36,13,±20
4,1st grade,134,±68,"1,837",±323,63,±52,56,±62,22,...,627,±243,25,±30,30,±24,189,±117,487,±181

In [149]:
education_2015["Label (Grouping)"].tolist()

['Total:',
 '\xa0\xa0\xa0\xa0No schooling completed',
 '\xa0\xa0\xa0\xa0Nursery school',
 '\xa0\xa0\xa0\xa0Kindergarten',
 '\xa0\xa0\xa0\xa01st grade',
 '\xa0\xa0\xa0\xa02nd grade',
 '\xa0\xa0\xa0\xa03rd grade',
 '\xa0\xa0\xa0\xa04th grade',
 '\xa0\xa0\xa0\xa05th grade',
 '\xa0\xa0\xa0\xa06th grade',
 '\xa0\xa0\xa0\xa07th grade',
 '\xa0\xa0\xa0\xa08th grade',
 '\xa0\xa0\xa0\xa09th grade',
 '\xa0\xa0\xa0\xa010th grade',
 '\xa0\xa0\xa0\xa011th grade',
 '\xa0\xa0\xa0\xa012th grade, no diploma',
 '\xa0\xa0\xa0\xa0Regular high school diploma',
 '\xa0\xa0\xa0\xa0GED or alternative credential',
 '\xa0\xa0\xa0\xa0Some college, less than 1 year',
 '\xa0\xa0\xa0\xa0Some college, 1 or more years, no degree',
 "\xa0\xa0\xa0\xa0Associate's degree",
 "\xa0\xa0\xa0\xa0Bachelor's degree",
 "\xa0\xa0\xa0\xa0Master's degree",
 '\xa0\xa0\xa0\xa0Professional school degree',
 '\xa0\xa0\xa0\xa0Doctorate degree']

In [150]:
education_2015_est = education_2015[
    ["Label (Grouping)"] +
    [col for col in education_2015.columns if "!!Estimate" in col]
]

In [151]:
total_row_2015 = education_2015_est.iloc[[0]]

college_rows_2015 = education_2015_est.iloc[[21, 22, 23, 24]]

In [152]:
total_numeric_2015 = (
    total_row_2015
    .replace(",", "", regex=True)
    .apply(pd.to_numeric, errors="coerce")
)

college_numeric_2015 = (
    college_rows_2015
    .replace(",", "", regex=True)
    .apply(pd.to_numeric, errors="coerce")
)

In [153]:
college_total_2015 = college_numeric_2015.sum(axis=0)

college_pct_2015 = (
    college_total_2015 / total_numeric_2015.iloc[0]
) * 100

In [154]:
college_pct_2015.head()

Label (Grouping)                                    NaN
Abilene, TX Metro Area!!Estimate              21.625544
Aguadilla-Isabela, PR Metro Area!!Estimate    19.754486
Akron, OH Metro Area!!Estimate                29.414896
Albany, GA Metro Area!!Estimate               17.627727
dtype: float64

In [155]:
education_2015_tidy = college_pct_2015.reset_index()

education_2015_tidy.columns = [
    "CensusMetro",
    "CollegeEducatedPct2015"
]

education_2015_tidy["CensusMetro"] = (
    education_2015_tidy["CensusMetro"]
    .str.replace(" Metro Area!!Estimate", "", regex=False)
)

In [156]:
education_2015_tidy.head()

             CensusMetro  CollegeEducatedPct2015
0       Label (Grouping)                     NaN
1            Abilene, TX               21.625544
2  Aguadilla-Isabela, PR               19.754486
3              Akron, OH               29.414896
4             Albany, GA               17.627727

In [157]:
education_2015_tidy.shape

(389, 2)

In [158]:
education_2015_tidy.dtypes

CensusMetro                object
CollegeEducatedPct2015    float64
dtype: object

In [159]:
education_2015_tidy = education_2015_tidy.dropna(
    subset=["CollegeEducatedPct2015"]
).reset_index(drop=True)

In [160]:
education_2015_tidy.shape

(388, 2)

In [161]:
education_2015_tidy.head()

             CensusMetro  CollegeEducatedPct2015
0            Abilene, TX               21.625544
1  Aguadilla-Isabela, PR               19.754486
2              Akron, OH               29.414896
3             Albany, GA               17.627727
4             Albany, OR               17.312990

In [162]:
analysis_2015_top100.shape

(100, 14)

In [164]:
analysis_2015_top100 = analysis_2015_top100.merge(
    education_2015_tidy,
    left_on="CensusMetro2015",
    right_on="CensusMetro",
    how="left"
)

In [165]:
analysis_2015_top100.shape

(100, 16)

In [166]:
analysis_2015_top100["CollegeEducatedPct2015"].isna().sum()

np.int64(0)

In [167]:
analysis_2015_top100["PriceToIncomeRatio2015"] = (
    analysis_2015_top100["HomeValue"]
    / analysis_2015_top100["Income2015"]
)

In [168]:
analysis_2015_top100[
    [
        "RegionName",
        "HomeValue",
        "Income2015",
        "Population2015",
        "CollegeEducatedPct2015",
        "PriceToIncomeRatio2015"
    ]
].head(10)

,RegionName,HomeValue,Income2015,Population2015,CollegeEducatedPct2015,PriceToIncomeRatio2015
0,"New York, NY",428263.745008,67296,19979950,37.538252,6.363881
1,"Los Angeles, CA",505439.753601,60705,13154457,32.047655,8.326163
2,"Chicago, IL",207197.138214,61828,9534008,35.460986,3.351186
3,"Dallas, TX",198993.505462,59946,6833420,32.508212,3.319546
4,"Houston, TX",196240.731321,59649,6346653,30.673618,3.289925
5,"Washington, DC",387927.724986,92324,5949403,48.892058,4.201808
6,"Philadelphia, PA",216141.501149,62513,6035680,34.785571,3.457545
7,"Miami, FL",236156.840184,48745,5861000,29.745052,4.844740
8,"Atlanta, GA",188607.438303,57000,5535837,35.849491,3.308902
9,"Boston, MA",410524.555428,75389,4694565,44.635601,5.445417

In [169]:
analysis_2015_top100[
    [
        "HomeValue",
        "Income2015",
        "Population2015",
        "CollegeEducatedPct2015",
        "PriceToIncomeRatio2015"
    ]
].isna().sum()

HomeValue                 0
Income2015                0
Population2015            0
CollegeEducatedPct2015    0
PriceToIncomeRatio2015    0
dtype: int64

In [170]:
analysis_2015_top100.to_csv(
    "Data Intermediate/analysis_2015_top100.csv",
    index=False
)